apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradle-spring-boot
  labels:
    app: gradle-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot
        image: gcr.io/terraform-265913/spring-boot
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: spring-boot
spec:
  selector:
    app: spring-boot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer